"""Renderer adapter: BlueMap's command-line version, run as a separate Java program.

BlueMap never gets a path into the archive. Its workspace (paths.render_dir) holds::

    config/               BlueMap configuration, regenerated by mcatlas on every run
    data/                 BlueMap's own runtime data (render progress, Minecraft client jar)
    worlds/<world id>/    copies of the files the maps need; the only worlds BlueMap reads
    web/                  the BlueMap viewer with its tiles (served under /3d/ by `mcatlas serve`)
    flat/<map id>/<n>.png flat top-down image of area n, stitched from BlueMap's low-res tiles
    mcatlas-renders.json  which maps were rendered, from which plan

All writes go through the output guard. BlueMap's metrics reporting is switched off.
"""

import contextlib
import io
import json
import os
import re
import shutil
import subprocess
import zipfile
from collections.abc import Callable, Collection, Mapping, Sequence
from datetime import UTC, datetime
from pathlib import Path
from typing import IO, Final, cast

from PIL import Image
from pydantic import BaseModel, Field, ValidationError

from mcatlas.adapters.guard import check_output_path
from mcatlas.adapters.outputs import atomic_write, remove
from mcatlas.core.model import NETHER, OVERWORLD, WorldId
from mcatlas.core.render import RENDER_VERSION, MapPlan, RenderArea, RenderedMap

INDEX: Final = "mcatlas-renders.json"
LOWRES_TILE: Final = 500
_LODS: Final = ((1, 1), (2, 5), (3, 25))
"""BlueMap's low-res levels: (level, blocks per pixel)."""
MAX_IMAGE_SIDE: Final = 4096
BATCH: Final = 8
"""Maps per BlueMap run; the index is saved after every run, so an interrupted render keeps
what it finished."""

_LOOK: Final[Mapping[str, Mapping[str, object]]] = {
    OVERWORLD: {"sky-color": "#7dabff", "void-color": "#000000", "ambient-light": 0.1},
    NETHER: {"sky-color": "#290000", "void-color": "#150000", "ambient-light": 0.6},
}
_END_LOOK: Final[Mapping[str, object]] = {
    "sky-color": "#080010",
    "void-color": "#080010",
    "ambient-light": 0.6,
}


_TILE_PATH: Final = re.compile(r"/maps/([A-Za-z0-9_]+)/tiles/")


class RenderError(RuntimeError):
    pass


class _Index(BaseModel):
    version: int
    maps: list[RenderedMap] = Field(default_factory=list[RenderedMap])


def tile_path(x: int, z: int) -> str:
    """BlueMap's file layout for tile (x, z): a folder per digit, e.g. (-17, 3) -> x-1/7/z3."""
    parts: list[str] = []
    current = ""
    for c in f"x{x}z{z}":
        current += c
        if c.isdigit():
            parts.append(current)
            current = ""
    return "/".join(parts)


def _relative_world_path(relpath: str) -> Path:
    path = Path(relpath)
    if path.is_absolute() or ".." in path.parts or not relpath:
        raise ValueError(f"unsafe path inside a world: {relpath!r}")
    return path


def _hocon(value: object) -> str:
    # HOCON is a superset of JSON, so JSON is a valid BlueMap config file.
    return json.dumps(value, indent=2, ensure_ascii=False) + "\n"


def _mask(area: RenderArea) -> dict[str, int]:
    x0, z0, x1, z1 = area.box
    mask = {"min-x": x0, "max-x": x1, "min-z": z0, "max-z": z1}
    if area.max_y is not None:
        mask["max-y"] = area.max_y
    return mask


def _marker(area: RenderArea, height: int | None) -> dict[str, object]:
    y = (height if height is not None else area.y) + 1
    return {
        "type": "poi",
        "label": area.label.capitalize(),
        "detail": f"<b>{area.label.capitalize()}</b><br>{area.detail}",
        "position": {"x": area.x + 0.5, "y": y, "z": area.z + 0.5},
        "max-distance": 100_000,
    }


def stitch(tiles: Path, box: tuple[int, int, int, int]) -> bytes | None:
    """A flat image of `box` from BlueMap's low-res tiles (1 pixel per block when it fits)."""
    x0, z0, x1, z1 = box
    lod, per_px = next(
        (
            (lod, per_px)
            for lod, per_px in _LODS
            if max(x1 - x0, z1 - z0) // per_px < MAX_IMAGE_SIDE
        ),
        _LODS[-1],
    )
    px0, pz0, px1, pz1 = x0 // per_px, z0 // per_px, x1 // per_px, z1 // per_px
    canvas = Image.new("RGBA", (px1 - px0 + 1, pz1 - pz0 + 1))
    for tx in range(px0 // LOWRES_TILE, px1 // LOWRES_TILE + 1):
        for tz in range(pz0 // LOWRES_TILE, pz1 // LOWRES_TILE + 1):
            path = tiles / str(lod) / f"{tile_path(tx, tz)}.png"
            if not path.is_file():
                continue
            with Image.open(path) as tile:
                # The top half holds colours; the bottom half heights and light.
                colours = tile.convert("RGBA").crop((0, 0, LOWRES_TILE, LOWRES_TILE))
            canvas.paste(colours, (tx * LOWRES_TILE - px0, tz * LOWRES_TILE - pz0))
    if canvas.getbbox() is None:
        return None
    out = io.BytesIO()
    canvas.save(out, format="PNG", optimize=True)
    return out.getvalue()


def surface_height(tiles: Path, x: int, z: int) -> int | None:
    """Height of the top block at (x, z), read from the bottom half of a low-res tile."""
    tx, tz = x // LOWRES_TILE, z // LOWRES_TILE
    path = tiles / "1" / f"{tile_path(tx, tz)}.png"
    if not path.is_file():
        return None
    px, pz = x - tx * LOWRES_TILE, z - tz * LOWRES_TILE
    with Image.open(path) as tile:
        rgba = tile.convert("RGBA")
        colour = cast("tuple[int, int, int, int]", rgba.getpixel((px, pz)))
        meta = cast("tuple[int, int, int, int]", rgba.getpixel((px, pz + LOWRES_TILE + 1)))
    if colour[3] == 0:
        return None
    height = (meta[1] << 8) | meta[2]  # red is block light; green/blue a signed 16-bit height
    return height - 0x10000 if height >= 0x8000 else height


class BlueMapRenderer:
    def __init__(
        self,
        workspace: Path,
        *,
        java: Path | None,
        jar: Path | None,
        client_jar: Path | None = None,
        accept_download: bool = False,
        mc_version: str | None = None,
        threads: int = 0,
    ) -> None:
        self._dir = check_output_path(workspace)
        self._java = java
        self._jar = jar
        self._client_jar = client_jar
        self._accept_download = accept_download
        self._mc_version = mc_version
        self._threads = threads

    # -- copies of worlds ---------------------------------------------------------------

    def _world_dir(self, world_id: WorldId) -> Path:
        return self._dir / "worlds" / _relative_world_path(world_id)

    def staged(self, world_id: WorldId) -> Mapping[str, tuple[int, int]]:
        root = self._world_dir(world_id)
        found: dict[str, tuple[int, int]] = {}
        for folder, _dirs, files in os.walk(root):
            for name in files:
                if name.startswith("."):
                    continue
                st = (Path(folder) / name).stat()
                rel = (Path(folder) / name).relative_to(root).as_posix()
                found[rel] = (st.st_size, st.st_mtime_ns)
        return found

    def stage(self, world_id: WorldId, relpath: str, data: bytes, mtime_ns: int) -> None:
        target = atomic_write(self._world_dir(world_id) / _relative_world_path(relpath), data)
        os.utime(target, ns=(mtime_ns, mtime_ns))

    def unstage(self, world_id: WorldId, keep: Collection[str]) -> int:
        removed = 0
        for rel in set(self.staged(world_id)) - set(keep):
            remove(self._world_dir(world_id) / rel)
            removed += 1
        return removed

    # -- rendering ------------------------------------------------------------------------

    def _load_index(self) -> list[RenderedMap]:
        try:
            index = _Index.model_validate_json((self._dir / INDEX).read_bytes())
        except OSError, ValidationError:
            return []
        return index.maps if index.version == RENDER_VERSION else []

    def _save_index(self, maps: Sequence[RenderedMap]) -> None:
        index = _Index(version=RENDER_VERSION, maps=sorted(maps, key=lambda m: m.map_id))
        atomic_write(self._dir / INDEX, index.model_dump_json(indent=1).encode())

    def rendered(self) -> list[RenderedMap]:
        return self._load_index()

    def image(self, path: str) -> bytes:
        rel = _relative_world_path(path)
        if rel.parts[0] != "flat":
            raise ValueError(f"not a flat map image: {path!r}")
        return (self._dir / rel).read_bytes()

    def _mc_version_and_client(self) -> str | None:
        if self._client_jar is None:
            return self._mc_version
        try:
            with zipfile.ZipFile(self._client_jar) as jar:
                info = cast("dict[str, object]", json.loads(jar.read("version.json")))
        except (OSError, KeyError, ValueError, zipfile.BadZipFile) as e:
            raise RenderError(f"not a Minecraft client jar: {self._client_jar} ({e})") from e
        version = str(info.get("id") or "")
        if not version or "/" in version:
            raise RenderError(f"no version id in {self._client_jar}")
        target = self._dir / "data" / f"minecraft-client-{version}.jar"
        if not target.is_file() or target.stat().st_size != self._client_jar.stat().st_size:
            atomic_write(target, self._client_jar.read_bytes())
        return self._mc_version or version

    def _write_config(
        self, plans: Sequence[MapPlan], heights: Mapping[str, Mapping[int, int]]
    ) -> None:
        config = self._dir / "config"
        core = {
            "accept-download": self._accept_download,
            "data": str(self._dir / "data"),
            "render-thread-count": self._threads,
            "scan-for-mod-resources": False,
            "metrics": False,
            "log": {"file": str(self._dir / "data" / "logs" / "debug.log"), "append": False},
        }
        webapp = {
            "enabled": True,
            "webroot": str(self._dir / "web"),
            "update-settings-file": True,
            "use-cookies": True,
            "default-to-flat-view": False,
            # The viewer unpacks tiles itself, so any static web server can serve it.
            "client-decompression": True,
            "scripts": list[str](),
            "styles": list[str](),
        }
        storage = {"storage-type": "file", "root": str(self._dir / "web" / "maps")}
        atomic_write(config / "core.conf", _hocon(core).encode())
        atomic_write(config / "webapp.conf", _hocon(webapp).encode())
        atomic_write(config / "storages" / "file.conf", _hocon(storage).encode())
        wanted = {f"{p.map_id}.conf" for p in plans}
        maps = config / "maps"
        if maps.is_dir():
            for stale in maps.glob("*.conf"):
                if stale.name not in wanted:
                    remove(stale)
        for plan in plans:
            conf = self._map_config(plan, heights.get(plan.map_id, {}))
            atomic_write(maps / f"{plan.map_id}.conf", _hocon(conf).encode())

    def _map_config(self, plan: MapPlan, heights: Mapping[int, int]) -> dict[str, object]:
        start = plan.areas[0]
        return {
            "world": str(self._world_dir(plan.world_id)),
            "dimension": plan.dimension,
            "name": plan.name,
            "sorting": plan.sorting,
            "start-pos": {"x": start.x, "z": start.z},
            **_LOOK.get(plan.dimension, _END_LOOK),
            "sky-light": 1,
            "remove-caves-below-y": -10_000 if plan.show_caves else 55,
            "cave-detection-ocean-floor": -5,
            "min-inhabited-time": 0,
            "render-mask": [_mask(a) for a in plan.areas],
            "render-edges": True,
            "edge-light-strength": 8,
            "enable-perspective-view": True,
            "enable-flat-view": True,
            "enable-free-flight-view": True,
            "enable-hires": True,
            "storage": "file",
            "marker-sets": {
                "mcatlas": {
                    "label": "Bouwplekken",
                    "toggleable": True,
                    "default-hidden": False,
                    "markers": {
                        f"area-{i}": _marker(a, heights.get(i)) for i, a in enumerate(plan.areas)
                    },
                }
            },
        }

    def _command(
        self, action: str, map_ids: Sequence[str], version: str | None, *, force: bool = False
    ) -> list[str]:
        java = str(self._java) if self._java else shutil.which("java")
        if java is None:
            raise RenderError("no Java found: set render.java (BlueMap 5.17+ needs Java 25)")
        if self._jar is None or not self._jar.is_file():
            raise RenderError(f"BlueMap CLI jar not found: set render.jar ({self._jar})")
        command = [java, "-jar", str(self._jar), "-c", str(self._dir / "config"), action]
        command += ["-m", ",".join(map_ids)]
        if version:
            command += ["-v", version]
        if force:
            command.append("-f")
        return command

    def _run(self, command: list[str], progress: Callable[[str], None]) -> set[str]:
        """Run BlueMap; return the maps for which it reported a tile it could not save."""
        tail: list[str] = []
        failed: set[str] = set()
        with subprocess.Popen(  # noqa: S603 - fixed program, arguments are our own paths
            command,
            cwd=self._dir,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            errors="replace",
        ) as process:
            output = cast("IO[str] | None", process.stdout)
            if output is None:  # pragma: no cover - stdout=PIPE always gives a stream
                raise RenderError("no output stream from BlueMap")
            for line in output:
                text = line.rstrip()
                if text:
                    tail = [*tail[-19:], text]
                    progress(text)
                    if "Exception" in text and (m := _TILE_PATH.search(text)):
                        failed.add(m[1])
        if process.returncode != 0:
            raise RenderError(f"BlueMap exited with {process.returncode}:\n" + "\n".join(tail))
        if any("must accept the required file download" in t for t in tail):
            raise RenderError(
                "BlueMap has no Minecraft client jar: set render.client_jar "
                "(or render.accept_download = true to let BlueMap download it)"
            )
        return failed

    def _settle_unsaved_tiles(self, map_id: str) -> int:
        """Handle tiles BlueMap wrote but could not move into place; return how many differ.

        On SMB shares the rename over an existing tile sometimes fails with "Resource busy"
        while the server still holds the old file (it happens for tiles on region borders,
        which are written more than once). The new version is left as `<tile>.filepart`.
        Identical ones are simply removed; different ones are counted and kept.
        """
        tiles = self._dir / "web" / "maps" / map_id / "tiles"
        differing = 0
        for part in tiles.rglob("*.filepart"):
            target = part.with_name(part.name.removesuffix(".filepart"))
            try:
                same = target.is_file() and target.read_bytes() == part.read_bytes()
            except OSError:
                same = False
            if same:
                with contextlib.suppress(OSError):
                    remove(part)
            else:
                differing += 1
        return differing

    def _images(self, plan: MapPlan) -> dict[int, str]:
        tiles = self._dir / "web" / "maps" / plan.map_id / "tiles"
        images: dict[int, str] = {}
        for i, area in enumerate(plan.areas):
            rel = f"flat/{plan.map_id}/{i}.png"
            png = stitch(tiles, area.box)
            if png is None:
                remove(self._dir / rel)
                continue
            atomic_write(self._dir / rel, png)
            images[i] = rel
        return images

    def render(
        self,
        plans: Sequence[MapPlan],
        todo: Collection[str],
        *,
        force: bool,
        progress: Callable[[str], None],
    ) -> list[RenderedMap]:
        check_output_path(self._dir).mkdir(parents=True, exist_ok=True)
        planned = {p.map_id: p for p in plans}
        for plan in plans:
            if not str(self._world_dir(plan.world_id)).startswith(str(self._dir)):
                raise RenderError(f"map {plan.map_id} would read outside the workspace")
        version = self._mc_version_and_client()
        index = {m.map_id: m for m in self._load_index() if m.map_id in planned}
        self._write_config(plans, {i: m.heights for i, m in index.items()})
        ids = [i for i in planned if i in todo]
        done: list[RenderedMap] = []
        for start in range(0, len(ids), BATCH):
            batch = ids[start : start + BATCH]
            failed = self._run(self._command("-r", batch, version, force=force), progress)
            stale = {m: self._settle_unsaved_tiles(m) for m in failed & set(batch)}
            for map_id, count in stale.items():
                if count:
                    progress(f"{map_id}: {count} tile(s) could not be replaced and are older")
            now = datetime.now(UTC)
            for map_id in batch:
                plan = planned[map_id]
                tiles = self._dir / "web" / "maps" / map_id / "tiles"
                heights = {
                    i: h
                    for i, a in enumerate(plan.areas)
                    if (h := surface_height(tiles, a.x, a.z)) is not None
                }
                result = RenderedMap.model_validate(
                    plan.model_dump()
                    | {
                        "rendered_at": now,
                        "images": self._images(plan),
                        "heights": heights,
                        "stale_tiles": stale.get(map_id, 0),
                    }
                )
                index[map_id] = result
                done.append(result)
            self._save_index(list(index.values()))
        if done:
            # Markers were configured before the heights were known; put them on the ground.
            self._write_config(plans, {i: m.heights for i, m in index.items()})
            self._run(self._command("--markers", [m.map_id for m in done], version), progress)
        else:
            self._save_index(list(index.values()))
        return done
